FROM node:21
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG API_PORT
ARG DOMAIN
ARG BACKEND_SUBDOMAIN
ARG VITE_API_BASE_URL
ENV API_PORT=$API_PORT
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV DOMAIN=$DOMAIN
ENV BACKEND_SUBDOMAIN=$BACKEND_SUBDOMAIN
EXPOSE 3000
CMD [ "node", "index.js" ]
